### ISSUE TITLE
Headless: true does not work

### ISSUE THREAD

**Issue by bvanderneut** [lirantal/cypress-social-logins#15]
Hello,

If I run it with:

```
headless: false
```

Everything works fine. But if I run it with

```
headless: true
```

I get this error message

```
CypressError: cy.task('GoogleSocialLogin') failed with the following error:

> Error: No node found for selector: #identifierNext
    at assert (C:\git\Independer\E2ETests\Cypress\node_modules\puppeteer\lib\helper.js:283:11)
    at DOMWorld.click (C:\git\Independer\E2ETests\Cypress\node_modules\puppeteer\lib\DOMWorld.js:366:5)
    at typeUsername (C:\git\Independer\E2ETests\Cypress\node_modules\cypress-social-logins\src\Plugins.js:70:3)
    at GoogleSocialLogin (C:\git\Independer\E2ETests\Cypress\node_modules\cypress-social-logins\src\Plugins.js:28:3)

  -- ASYNC --
    at Frame.<anonymous> (C:\git\Independer\E2ETests\Cypress\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (C:\git\Independer\E2ETests\Cypress\node_modules\puppeteer\lib\Page.js:1067:29)
    at typeUsername (C:\git\Independer\E2ETests\Cypress\node_modules\cypress-social-logins\src\Plugins.js:70:14)
    at GoogleSocialLogin (C:\git\Independer\E2ETests\Cypress\node_modules\cypress-social-logins\src\Plugins.js:28:3)
```

No qlue what is going wrong in headless mode. Maybe you know
Bjorn

**Comment by lirantal** [comment]
Hmm, not that I can think of off the top of my head.
I'll catch up on this next week but maybe someone else has an idea.. @raptatinha @michellelievsay

**Comment by michellelievsay** [comment]
I think this is an issue where a different google login UI is displayed when running headless. I was able to to see this by navigating directly to this link in incognito: [https://accounts.google.com/ServiceLogin?nojavascript=1](https://accounts.google.com/ServiceLogin?nojavascript=1). 

I won't be able to make a change for this for a while but updating the plugin to search for the next button and sign in buttons based on which UI is displayed seems to work for me. 

inside typeUsername()
```javascript
const found = (await page.content()).includes("One account. All of Google.");
const nextButton = found ? "#next" : "#identifierNext";
await page.click(nextButton);
```

and inside typePassword()
```javascript
const found = (await page.content()).includes("One account. All of Google.");
const signInButton = found ? "#signIn" : "#passwordNext";
await page.waitForSelector(signInButton, { visible: true });
await page.click(signInButton);
```
I bet there's a better solution to this, but I hope this is helpful for now!

**Comment by lirantal** [comment]
oh interesting! thanks for looking into it @michellelievsay ❤️
I can probably push out a fix for this for the google social login fairly easily in the next couple of days. Also @bvanderneut if you wanted to do that with a PR that would be great

**Comment by bvanderneut** [comment]
@lirantal I made a PR: https://github.com/lirantal/cypress-social-logins/pull/16

**Comment by vhbert** [comment]
Headless mode seems to be broken again.
```
cy.task('GoogleSocialLogin') failed with the following error:
> TimeoutError: waiting for selector ".logo__text" failed: timeout 30000ms exceeded
```
Not sure if I should make a new issue for this.
