### ISSUE TITLE
Navigation failed because browser has disconnected after updating OS

### ISSUE THREAD

**Issue by andieromero** [lirantal/cypress-social-logins#89]
After updating to Big Sur OS I'm getting `Navigation failed because browser has disconnected!` when running GoogleSocialLogin. It was definitely working before the update and a fresh install and code checkout on Catalina OS works for my peers. I checked that Chromium was enabled in the Firewall settings so I'm not sure why the browser would be closing unexpectedly. Any other ideas what would be causing this? Thanks!

Full stack trace:
```  at <unknown> (https://test.figure.com/__cypress/runner/cypress_runner.js:160102:20)
From previous event:
    at Context.task (https://test.figure.com/__cypress/runner/cypress_runner.js:160084:16)
From Your Spec Code:
    at Context.eval (webpack:///cypress/support/commands.js:63:15)
From Node.js Internals:
    Error: Navigation failed because browser has disconnected!
      at CDPSession.<anonymous> (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/LifecycleWatcher.js:46:108)
      at CDPSession.emit (events.js:315:21)
      at CDPSession._onClosed (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/Connection.js:215:11)
      at Connection._onClose (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/Connection.js:138:16)
      at WebSocket.<anonymous> (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/WebSocketTransport.js:48:23)
      at WebSocket.onClose (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/ws/lib/event-target.js:124:17)
      at WebSocket.emit (events.js:315:21)
      at WebSocket.emitClose (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/ws/lib/websocket.js:191:11)
      at Socket.socketOnClose (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/ws/lib/websocket.js:850:16)
      at Socket.emit (events.js:315:21)
      at TCP.<anonymous> (net.js:674:13)
      at Frame.<anonymous> (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/helper.js:111:16)
      at Page.goto (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/Page.js:672:50)
      at Page.<anonymous> (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/node_modules/puppeteer/lib/helper.js:112:24)
      at baseLoginConnect (/Users/andieromero/figure/frontend-cashout-refinance/node_modules/cypress-social-logins/src/Plugins.js:191:15)
      at processTicksAndRejections (internal/process/task_queues.js:97:6)
      at Object.wrapChildPromise (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:40:24)
      at Object.wrap (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:53:9)
      at task (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:127:13)
      at execute (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:140:45)
      at EventEmitter.<anonymous> (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:204:6)
      at EventEmitter.emit (events.js:315:21)
      at process.<anonymous> (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:23)
      at process.emit (events.js:315:21)
      at process.emit (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:22)
      at emit (internal/child_process.js:876:13)
      at processTicksAndRejections (internal/process/task_queues.js:85:22)
    From previous event:
      at Object.wrapParentPromise (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:13)
      at Object.task (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:116:24)
      at Object.execute (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:201:34)
      at <unknown> (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/task.js:28:23)
    From previous event:
      at Object.run (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/task.js:22:10)
      at backendRequest (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:425:28)
    From previous event:
      at Socket.<anonymous> (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:433:28)
      at Socket.emit (events.js:315:21)
      at <unknown> (/Users/andieromero/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:13)
      at processTicksAndRejections (internal/process/task_queues.js:79:12)```

**Comment by andieromero** [comment]
Upgrading Puppeteer from 2.1.1 -> 8.0.0 works. Can we update the package dependency to 8.0.0? I can't submit a PR to the repo, thank you!

**Comment by lirantal** [comment]
@andieromero new version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
